include:
  - project: flywheel-io/tools/etc/qa-ci
    file: ci/img.yml
    ref: master

# TODO remove publish:docker disable when ready to push
publish:docker:
  extends: .publish:docker
  rules:
    - when: never
