repos:
  - repo: git@gitlab.com:flywheel-io/tools/etc/qa-ci
    rev: master
    hooks:
      - id: test:flywheel-lint
      # TODO github just added a 60 request/hour rate-limit - fix resulting failures
      # https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
      # - id: update:repo
      - id: publish:docker:test
