repos:
  - repo: git@gitlab.com:flywheel-io/tools/etc/qa-ci
    rev: e069c62f44f0e564b0d721502632c605efc38573
    hooks:
      - id: test:flywheel-lint
      - id: test:pre-commit:isort
      - id: test:pre-commit:mypy
      - id: test:pre-commit:pylint
      - id: test:pre-commit:pylint-tests
      - id: test:pre-commit:pytest
      - id: publish:docker:test
      - id: test:pre-commit:pylint
      - id: test:pre-commit:pytest
